[platformio]
default_envs = esp32c6_dual

[env]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/54.03.21-2/platform-espressif32.zip
board = esp32-c6-devkitc-1
framework = arduino
monitor_speed = 115200
build_flags =
    -O2
    -fwrapv
    -I../../mcu-f12-microgpt/harness/include
    -Wno-unused-function
    -Wno-unused-variable
    -DFP_MATH_FORCE_PORTABLE
    -DMGPT_NO_TRAIN
    -DMGPT_NO_MAIN
    -DMGPT_PACKED_F12
    -DMGPT_OBSERVE_LOGITS
    -DMGPT_ESP32C6=1
    -DARDUINO_USB_CDC_ON_BOOT=0

[env:esp32c6_dual]
build_flags =
    ${env.build_flags}
    -DMGPT_FULL_DUAL=1
    -DMGPT_INCLUDE_WIDE=1
    -DMGPT_INCLUDE_PACKED=1
    -DMGPT_INCLUDE_CORRUPT=1

[env:esp32c6_wide]
build_flags =
    ${env.build_flags}
    -DMGPT_FULL_WIDE_ONLY=1
    -DMGPT_INCLUDE_WIDE=1
    -DMGPT_INCLUDE_PACKED=0
    -DMGPT_INCLUDE_CORRUPT=0

[env:esp32c6_packed]
build_flags =
    ${env.build_flags}
    -DMGPT_FULL_PACKED_ONLY=1
    -DMGPT_INCLUDE_WIDE=0
    -DMGPT_INCLUDE_PACKED=1
    -DMGPT_INCLUDE_CORRUPT=0
