[platformio]
default_envs = pico2_riscv_dual

[env]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git#aa70b802be8851668053d4f09734e4089fe41932
board = rpipico2
framework = arduino
monitor_speed = 115200
build_flags =
    -O2
    -fwrapv
    -I../../mcu-f12-microgpt/harness/include
    -Wno-unused-function
    -Wno-unused-variable
    -DFP_MATH_FORCE_PORTABLE
    -DMGPT_NO_TRAIN
    -DMGPT_NO_MAIN
    -DMGPT_PACKED_F12
    -DMGPT_OBSERVE_LOGITS

[env:pico2_arm_dual]
build_flags =
    ${env.build_flags}
    -DMGPT_PICO2_ARM=1
    -DMGPT_FULL_DUAL=1
    -DMGPT_INCLUDE_WIDE=1
    -DMGPT_INCLUDE_PACKED=1
    -DMGPT_INCLUDE_CORRUPT=1

[env:pico2_arm_wide]
build_flags =
    ${env.build_flags}
    -DMGPT_PICO2_ARM=1
    -DMGPT_FULL_WIDE_ONLY=1
    -DMGPT_INCLUDE_WIDE=1
    -DMGPT_INCLUDE_PACKED=0
    -DMGPT_INCLUDE_CORRUPT=0

[env:pico2_arm_packed]
build_flags =
    ${env.build_flags}
    -DMGPT_PICO2_ARM=1
    -DMGPT_FULL_PACKED_ONLY=1
    -DMGPT_INCLUDE_WIDE=0
    -DMGPT_INCLUDE_PACKED=1
    -DMGPT_INCLUDE_CORRUPT=0

[env:pico2_riscv_dual]
board_build.mcu = rp2350-riscv
build_flags =
    ${env.build_flags}
    -DMGPT_PICO2_RISCV=1
    -DMGPT_FULL_DUAL=1
    -DMGPT_INCLUDE_WIDE=1
    -DMGPT_INCLUDE_PACKED=1
    -DMGPT_INCLUDE_CORRUPT=1

[env:pico2_riscv_wide]
board_build.mcu = rp2350-riscv
build_flags =
    ${env.build_flags}
    -DMGPT_PICO2_RISCV=1
    -DMGPT_FULL_WIDE_ONLY=1
    -DMGPT_INCLUDE_WIDE=1
    -DMGPT_INCLUDE_PACKED=0
    -DMGPT_INCLUDE_CORRUPT=0

[env:pico2_riscv_packed]
board_build.mcu = rp2350-riscv
build_flags =
    ${env.build_flags}
    -DMGPT_PICO2_RISCV=1
    -DMGPT_FULL_PACKED_ONLY=1
    -DMGPT_INCLUDE_WIDE=0
    -DMGPT_INCLUDE_PACKED=1
    -DMGPT_INCLUDE_CORRUPT=0
